name: digital_stamp_quiz
description: "A basic quiz mobile application."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  go_router: ^14.0.2
  hooks_riverpod: ^2.5.1
  lottie: ^3.1.0
  riverpod: ^2.5.1
  get_it: ^7.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^1.1.0
  build_runner: ^2.1.3

flutter:
  uses-material-design: true

  assets:
    - assets/lotties/
    - assets/images/
    - assets/jsons/
    - assets/svgs/

  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DMSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
